before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "darwin"
      - "windows"
    goarch:
      - "arm64"
      - "amd64"
      - "386"
archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  disable: true
nfpms:
  - builds:
      - stew
    vendor: marwanhawari
    homepage: "https://github.com/marwanhawari/stew"
    maintainer: "Marwan Hawari <marwan.hawari@gmail.com>"
    description: "An independent package manager for compiled binaries"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
brews:
  - repository:
      owner: marwanhawari
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: Marwan Hawari
      email: marwan.hawari@gmail.com
    license: "MIT"
    homepage: "https://github.com/marwanhawari/stew"
    description: "An independent package manager for compiled binaries"
