version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "darwin"
      - "windows"
    goarch:
      - "arm64"
      - "amd64"
      - "386"
archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  disable: true
nfpms:
  - builds:
      - stew
    vendor: Jelloeater
    homepage: "https://github.com/Jelloeater/stew"
    maintainer: "Jelloeater <marwan.hawari@gmail.com>"
    description: "An independent package manager for compiled binaries"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
# brews:
#   - repository:
#       owner: Jelloeater
#       name: homebrew-tap
#     directory: Formula
#     commit_author:
#       name: Jelloeater
#       email: marwan.hawari@gmail.com
#     license: "MIT"
#     homepage: "https://github.com/Jelloeater/stew"
#     description: "An independent package manager for compiled binaries"
