before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "darwin"
      - "windows"
    goarch:
      - "arm64"
      - "amd64"
      - "386"
archives:
  - format: "binary"
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
