before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "darwin"
      - "windows"
    goarch:
      - "arm64"
      - "amd64"
      - "386"
archives:
  - format: "binary"
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
brews:
  - tap:
      owner: marwanhawari
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: Marwan Hawari
      email: marwan.hawari@gmail.com
    license: "MIT"
    homepage: "https://github.com/marwanhawari/stew"
    description: "An independent package manager for compiled binaries"
